name: CustomSpace
main: CustomSpaceTeam\CustomSpaceGuard\CustomSpace
api: [3.0.0]
version: 1.0
author: CustomSpaceTeam
website: https://github.com/CustomSpaceTeam/CustomSpaceGuard
commands:
  customspace:
    description: Opens up the User Interface of CustomSpace.
    aliases: ["csg"]
    default: op
  region:
    description: Create/Manage/Delete regions.
    aliases: ["crg"]
    default: op
softdepend: ["RedstoneCircuit"]
permissions:
  customspace.ui:
    default: op
  customspace.create:
    default: op
  customspace.modify:
    default: op
  customspace.delete:
    default: op
  customspace.enter:
    default: op
  customspace.leave:
    default: op
  customspace.place:
    default: op
  customspace.block-place:
    default: op
  customspace.break:
    default: op
  customspace.block-break:
    default: op
  customspace.edit:
    default: op
  customspace.eat:
    default: op
  customspace.drop:
    default: op
  customspace.deathdrop:
    default: op
  customspace.usechest:
    default: op
  customspace.usechestender:
    default: op
  customspace.usetrappedchest:
    default: op
  customspace.enchantingtable:
    default: op
  customspace.usedoors:
    default: op
  customspace.usegates:
    default: op
  customspace.usetrapdoors:
    default: op
  customspace.usefurnaces:
    default: op
  customspace.useanvil:
    default: op
  customspace.usecauldron:
    default: op
  customspace.usebrewingstand:
    default: op
  customspace.usebeacons:
    default: op
  customspace.usepressureplate:
    default: op
  customspace.useusebutton:
    default: op
  customspace.bypass.gamemode:
    default: op
